name: eggnstone_google_analytics
copyright: 2020-2025 Mark Eggenstein
description: A wrapper for Google Analytics. Allows to report via Firebase.
homepage: https://github.com/eggnstone/eggnstone_google_analytics
version: 4.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  eggnstone_dart: ^1.2.0
  #eggnstone_dart:
  #  path: ../eggnstone_dart
  eggnstone_flutter: ^4.1.0
  #eggnstone_flutter:
  #  path: ../eggnstone_flutter
  firebase_analytics: ^11.4.1
  firebase_analytics_platform_interface: ^4.3.1
  firebase_analytics_web: ^0.5.10+7

dev_dependencies:
  build_runner: ^2.4.14
  firebase_core: ^3.10.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
