name: eggnstone_google_analytics
copyright: 2020-2021 Mark Eggenstein
description: A wrapper for Google Analytics. Allows to report via Firebase.
homepage: https://github.com/eggnstone/eggnstone_google_analytics
version: 3.2.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter tools
  eggnstone_flutter: ^3.2.1
  #eggnstone_flutter:
  #  path: ../eggnstone_flutter

  # Firebase Analytics (NonWeb)
  firebase_analytics: ^8.3.2
  # Firebase Analytics (Web)
  firebase_analytics_web: ^0.3.0+1
  # Service locator (included via eggnstone_flutter but "flutter pub publish" warns if not included here)
  get_it: ^7.2.0

dev_dependencies:
  # Building mocks for Mockito
  build_runner: ^2.1.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  # Mocking/testing
  mockito: ^5.0.15
