name: eggnstone_google_analytics
copyright: 2020 Mark Eggenstein
description: Google analytics wrapper
homepage: https://eggnstone.dev
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter tools
  eggnstone_flutter: ^0.2.0
  #eggnstone_flutter:
  #  path: ..\eggnstone_flutter

  # Firebase Analytics (Web)
  firebase: ^7.3.0
  # Firebase Analytics (NonWeb)
  firebase_analytics: ^5.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mocking
  mockito: ^4.1.1

flutter:
