name: eggnstone_google_analytics
copyright: 2020-2021 Mark Eggenstein
description: A wrapper for Google Analytics. Allows to report via Firebase.
homepage: https://github.com/eggnstone/eggnstone_google_analytics
version: 2.0.0-pre2
#publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter tools
  eggnstone_flutter: ^2.0.0-pre2
  #eggnstone_flutter:
  #  path: ../eggnstone_flutter

  # Firebase Analytics (NonWeb)
  firebase_analytics: ^7.1.1
  # Firebase Analytics (Web)
  firebase_analytics_web: ^0.2.0+1
  # Service locator (included via eggnstone_flutter but "flutter pub publish" warns if not included here)
  get_it: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mocking
  mockito: any
